### ISSUE TITLE
Mobile Optimizations & Maybe Website redesign

### ISSUE THREAD

**Issue by smultar** [TheFutureGadgetsLab/WaifuXL#153]
![image](https://user-images.githubusercontent.com/6223536/172673594-e0b795e9-b0db-4c3b-b7e9-85c7bca6494f.png)
Going to be addressing some issues regarding mobile view spaces

**Comment by mario6714** [comment]
De: Smultar ***@***.***>
Enviado el: miércoles, 8 de junio de 2022 10:56 a. m.
Para: TheFutureGadgetsLab/WaifuXL ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [TheFutureGadgetsLab/WaifuXL] Mobile Optimizations (Issue #153)


[image]<https://user-images.githubusercontent.com/6223536/172673594-e0b795e9-b0db-4c3b-b7e9-85c7bca6494f.png>
Going to be addressing some issues regarding mobile view spaces

**Comment by haydn-jones** [comment]
@smultar Thanks for taking a stab at this, interested in seeing what you come up with. If you have anything in mind feel free to share something like a figma mockup so we can possibly collaborate on the UI design.

**Comment by smultar** [comment]
> @smultar Thanks for taking a stab at this, interested in seeing what you come up with. If you have anything in mind feel free to share something like a figma mockup so we can possibly collaborate on the UI design.

Add me on discord, I would love to have a collab session.
