### ISSUE TITLE
"Could not load model" on new version of the website

### ISSUE THREAD

**Issue by Thornus** [TheFutureGadgetsLab/WaifuXL#165]
![image](https://user-images.githubusercontent.com/17854170/227761338-c7388653-30d8-47b5-b0b6-07d5a951de0f.png)

"An unexpected error has occurred. Please refresh the page. If the problem persists, please submit an issue [here](https://github.com/TheFutureGadgetsLab/WaifuXL/issues).
Could not load model."

when trying to upscale an image to 2x

**Comment by bensonalec** [comment]
Hi Thornus, looking into this now! I'll let you know if i need any more information!

**Comment by bensonalec** [comment]
Hi Thornus, as I should've expected, everything seems to have broken in multiple ways on the deployment. Working t resolve them, but for now I'd suggest using https://de-spaghetti.waifuxl.pages.dev/ in order to work with WaifuXL.

**Comment by Thornus** [comment]
Thank you so much!

**Comment by haydn-jones** [comment]
I'm fairly certain this was simply a cloudflare caching issue. Can you try again and let us know how it goes?

**Comment by Thornus** [comment]
Tried on Chrome regular session and incognito. The regular session still has the problem, but incognito worked!

**Comment by bensonalec** [comment]
Sounds like something is cached, so you'll want to clear the cache and cookies for WaifuXL. Glad it seems to be working now!
