### ISSUE TITLE
~4x slower upscaling compared to hosted site

### ISSUE THREAD

**Issue by tom-leamon** [TheFutureGadgetsLab/WaifuXL#171]
I'm facing an issue where on your hosted site https://waifuxl.com/ upscaling takes about 7-15s, but when I clone the repository the identical upscales take 60s+. This occurs even when running in production mode. Any suggestions? Thank you.

Great work, it's amazing to see real-esrgan running the the browser.

**Comment by tom-leamon** [comment]
The CPU usage for https://waifuxl.com/ goes up to ~80% on my computer, but doesn't rise above 30% locally.

**Comment by tom-leamon** [comment]
I figured it out. To take advantage of hardware concurrency the site needs to be served over HTTPS and some specific security headers need to be sent. This has to do with the Spectre/Meltdown vulnerability of 2018.

The headers I needed were Cross-Origin-Embedder-Policy: require-corp and Cross-Origin-Opener-Policy: same-origin. You can actually set these headers quite easily in the next.config.js file.

```javascript
// next.config.js
module.exports = {
  async headers() {
    return [
      {
        // Apply these headers to all routes in your application.
        source: '/(.*)',
        headers: [
          {
            key: 'Cross-Origin-Embedder-Policy',
            value: 'require-corp',
          },
          {
            key: 'Cross-Origin-Opener-Policy',
            value: 'same-origin',
          },
        ],
      },
    ]
  },
}
```

I made a fork of this project that lets you do batches of upscales and persist everything using IndexedDb. Thank you for the amazing work porting Real-ESRGAN to the web!

**Comment by haydn-jones** [comment]
Hey @tom-leamon, sorry we took so long to get back, we probably could have saved you some time. You definitely came to the right conclusion with the headers, we have to serve those through cloudflare. If you'd like to submit a PR with the header changes for local runs we'd love to merge it.
